---
title: "Copula Markov Models"
output: pdf_document
---

## 1. Introduction

 A Copula Markov Model (CMM) of order one defines the joint law of the pairs $(X_{t-1}, X_t)$:

\[ 
F(x_{t-1}, x_t) \sim C(F(x_{t-1}), F(x_t)) 
\]

The Markov property leads to:

\[
f(x_1, \dots, x_n) = f(x_1) \prod_{t=2}^n f(x_t \mid x_{t-1}) 
\]

Using the copula density \(c(u_{t-1}, u_t) = \frac{\partial^2}{\partial x_{t-1} \partial x_t} C(u_{t-1}, u_t)\) and taking \(u_t = F(x_t)\), we can also write:

\[
f(x_t \mid x_{t-1}) = \frac{f(x_{t-1}, x_t)}{f(x_{t-1})} = \frac{c(u_{t-1}, u_t) f(x_{t-1}) f(x_t)}{f(x_{t-1})}
\] which leads to:

\[
f(x_1, \dots, x_n) = f(x_1) \prod_{t=2}^n f(x_t) c(u_{t-1}, u_t) = \prod_{t=1}^n f(x_t) \prod_{t=2}^n c(u_{t-1}, u_t)
\]

The joint copula density is:

\[
c_n(u_1,\dots,u_n) = \frac{f(x_1,\dots,x_n)}{\prod_{t=1}^n f(x_t)} = \frac{\prod_{t=1}^n f(x_t) \prod_{t=2}^n c(u_{t-1}, u_t)}{\prod_{t=1}^n f(x_t)} = \prod_{t=2}^n c(u_{t-1}, u_t)
\]

The joint copula is then given by:

\[C_n(u_1,\dots,u_n) = \int_0^{u_1} \dots \int_0^{u_n} \prod_{t=2}^n c(v_{t-1}, v_t) dv_1 \dots dv_n\]

We can write the diagonal as:

\[\delta_n(u) = C_n(u,\dots,u) = \int_0^{u} \dots \int_0^{u} \prod_{t=2}^n c(v_{t-1}, v_t) dv_1 \dots dv_n\]

The iid case for example is given by \(c(v_{t-1}, v_t) = 1\):

\[
\delta_n(u) = \int_0^{u} \dots \int_0^{u} 1 dv_1, \dots, dv_n = u^n
\]